cargo-features = ["edition"]

[package]
name = "parser"
version = "0.1.0"
authors = ["Vincent Isambart <vincent.isambart@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.7.8"
lazy_static = "1.1.0"
